export {default as NavBar} from './navBar/NavBar'
export {default as Footer} from './footer/Footer'
export {default as HeroSection} from './heroSection/HeroSection'
export {default as Properties} from './properties/Properties'
export {default as ServicesList} from './servicesList/ServicesList'
export {default as Testimonials} from './testimonials/Testimonials'
export {default as FAQ} from './faq/FAQ'
export {default as CTA} from './cta/CTA'